APP:
  INTERACTIVE: true
  WHOIS_SLEEP_TIME: 30
  EXPIRE_DAYS_THRESHOLD: 30
  ZULIP_BOT_FILE: ".zuliprc"
  ZULIP_STREAM: "domain-expiry-tracking"
  ZULIP_ERROR_STREAM: "script-errors"
  DEBUG: true
  DOMAINS:
    - "example.co.uk"
    - "example.com"
  NOTIFICATIONS:
    - "ZulipAPI"
    - "Email"
  SCRIPT_MONITORING:
    - 'Zabbix'
  ZABBIX_CONFIG_FILE: "/etc/zabbix/zabbix_agent2.conf"
  SERVER_NAME: "server.example.com"
  SMTP_SERVER: "smtp.example.com"
  SMTP_PORT: 25
  SMTP_FROM: "no-reply@example.com"
  SMTP_SEND_TO: "example@example.com"